name: CI

on: [push]

jobs:
  linux:
    name: build

    runs-on: ubuntu-18.04

    steps:
    - name: PokerTH git repo checkout
      uses: actions/checkout@v2

    # Build PokerTH
    # Note that if the build failes, caches won't get stored, so it might be sensible to disable the build
    # when adding new dependencies
    - name: Build
      run: |
        cd .github/actions/builder/
        ./build.sh
    
    # Upload the build artifact to GHA so it can be downloaded on the GHA Action page
    # See docs here: https://github.com/actions/upload-artifact 
    - uses: actions/upload-artifact@v2
      with:
        name: pokerth-client
        path: path/to/pokerth-client-binary
        
    - uses: actions/upload-artifact@v2
      with:
        name: pokerth-server
        path: path/to/pokerth-server-binary    
  
  mac:
    name: build

    runs-on: macos-10.15

    steps:
    - name: PokerTH git repo checkout
      uses: actions/checkout@v2

    # Build PokerTH
    # Note that if the build failes, caches won't get stored, so it might be sensible to disable the build
    # when adding new dependencies
    - name: Build
      run: |
        cd .github/actions/builder/
        ./build.sh

    # Upload the build artifact to GHA so it can be downloaded on the GHA Action page
    - uses: actions/upload-artifact@v2
      with:
        name: pokerth-client
        path: path/to/pokerth-client-binary
        
    - uses: actions/upload-artifact@v2
      with:
        name: pokerth-server
        path: path/to/pokerth-server-binary
      