name: CI

on: [push]

jobs:
  ci:
    name: build

    runs-on: ubuntu-18.04

    steps:
    - name: PokerTH git repo checkout
      uses: actions/checkout@v2

    # Build PokerTH
    # Note that if the build failes, caches won't get stored, so it might be sensible to disable the build
    # when adding new dependencies
    - name: Build
      run: |
        cd .github/actions/builder/
        ./linux-build.sh
